### PR TITLE
auto config generation idea and minor updates to README

### PR DESCRIPTION
**Pull request by SpudGunMan**
saw a typo to correct

### CODE REVIEW

**Review by smr99 — COMMENTED** [review]
I like the idea of making things more automated.  Are you using either of the hubstatus or hubcontrol tools?  It would be neat if one could edit the BT address there, for example.

In a semi-related note, I was re-reading the contributed patches yesterday.  Folks on non-linux platforms are sending patches to remove the automatic discovery -- both USB and BT -- because it is using linux-only things like pyudev.  The auto-discover can be avoided by selecting the appropriate ConnectionMonitor.  I realised today that the reason for the patches may well be that this fact is not very apparent.  So I think I'll move connection into the configuration itself, with some kind of platform-dependent defaulting.

**Comment by SpudGunMan** [comment]
yea going away with libraries is always cool an idea for you there is why not ask for a port if its a int = COM if its str then use the linux/osx device name for the connecting port

**Comment by SpudGunMan** [comment]
here is how I plan to use the port if it seems stable after some use can add it to the readme, saw your other comment will check it out in a bit https://github.com/SpudGunMan/SpudGunMan/blob/main/Lego/pi2hub.sh

**Comment by SpudGunMan** [comment]
minimized it down to just the readme changes

**Comment by SpudGunMan** [comment]
I am closing this to make a new pull

**Pull request closed without merging**
